/**
 * Filter pipeline for the Matrix Kehadiran page.
 *
 * Pure module: NO React, MUI, or DOM imports. All functions are
 * deterministic and side-effect-free so they can be exercised by
 * property-based tests without a renderer or window.
 *
 * Design reference:
 *   .kiro/specs/matrix-kehadiran-dark-redesign/design.md
 *     §"Search and filters"
 *     §"Derived data pipeline" (filterEmployees → visibleEmployees)
 *
 * The pipeline filters *employees* only — `days` and the cell-geometry math
 * derived from `(viewportWidth, breakpoint, expanded, days.length)` are
 * deliberately untouched. This is what Property 9 ("Filter purity — column
 * geometry stability") asserts: applying filters must not affect column
 * widths or the `days` array reference.
 *
 * Requirements: 3.9, 5.13, 5.14, 9.4, 9.5.
 */

import type {
  AttendanceRecord,
  Employee,
  QuickFilterState,
} from '../types';

// ─── matchEmployee ─────────────────────────────────────────────────────────

/**
 * Case-insensitive substring match for an employee against a search query.
 *
 * Behaviour:
 *   - Empty or whitespace-only `query` → returns `true` (no filter applied).
 *   - Otherwise the query is trimmed and lowercased, and matches when it
 *     occurs as a substring of either `emp.name` or `emp.employeeId`
 *     (both lowercased).
 *
 * The `name` lookup uses `String(emp.name ?? '')` so the function is
 * defensive against partially-populated `Employee` records (e.g. fixtures
 * generated by property-based tests with optional fields).
 *
 * Requirements: 3.9.
 */
export function matchEmployee(emp: Employee, query: string): boolean {
  const trimmed = query.trim();
  if (trimmed.length === 0) return true;

  const needle = trimmed.toLowerCase();
  const name = String(emp.name ?? '').toLowerCase();
  const id = String(emp.employeeId ?? '').toLowerCase();

  return name.includes(needle) || id.includes(needle);
}

// ─── applyFilters ──────────────────────────────────────────────────────────

/**
 * Result shape for `applyFilters`. The `employees` array and `attendance`
 * map are *new* references; the caller can compare reference identity to
 * confirm filter purity (Property 9).
 */
export interface FilterResult {
  employees: Employee[];
  attendance: Map<string, AttendanceRecord>;
}

/**
 * Filter employees and the attendance map based on the search box, the
 * top-of-table department selector, and the Right_Insight_Panel quick
 * filters. Returns *new* `Employee[]` and `Map` references — the input
 * collections are never mutated.
 *
 * Filter dimensions (composed with logical AND):
 *   1. `matchEmployee(emp, search)` — case-insensitive name/id substring.
 *   2. `departmentFilter === 'all' || emp.department === departmentFilter`
 *      — top-of-table dropdown.
 *   3. `quickFilters.department === 'all' || emp.department === q.department`
 *      — Right_Insight_Panel "Departemen" dropdown.
 *   4. `quickFilters.location` — **informational only for now**. The
 *      `Employee` type does not currently carry a `location` field, so this
 *      dimension is treated as `'all'` regardless of selection. When/if a
 *      `location` field is added to `Employee`, this branch should be
 *      activated and Property 9 must continue to hold.
 *   5. `quickFilters.status` — applies to *records*, not employees, so it
 *      does not reduce the employee set here. Cell-level rendering can
 *      apply the status filter at draw time if needed.
 *
 * The returned `attendance` map contains only entries whose `employeeId`
 * survives the filter — the `days` array (and therefore column geometry)
 * is untouched. This is the key invariant that makes Property 9 hold:
 * cell width depends on `days.length` and viewport math, both of which
 * are independent of `applyFilters`.
 *
 * Requirements: 3.9, 5.13, 5.14, 9.4, 9.5.
 */
export function applyFilters(
  employees: Employee[],
  attendance: Map<string, AttendanceRecord>,
  search: string,
  departmentFilter: string,
  quickFilters: QuickFilterState,
): FilterResult {
  const filteredEmployees: Employee[] = [];
  const survivors = new Set<string>();

  for (const emp of employees) {
    if (!matchEmployee(emp, search)) continue;

    if (departmentFilter !== 'all' && emp.department !== departmentFilter) {
      continue;
    }

    if (
      quickFilters.department !== 'all' &&
      emp.department !== quickFilters.department
    ) {
      continue;
    }

    // quickFilters.location: informational only — the Employee type does
    // not carry a location field today, so we cannot filter on it. When
    // the field is added, replace this no-op with a real comparison.
    // quickFilters.status: applies to records, not employees — skipped here.

    filteredEmployees.push(emp);
    survivors.add(emp.employeeId);
  }

  const filteredAttendance = new Map<string, AttendanceRecord>();
  for (const [key, value] of attendance) {
    if (survivors.has(value.employeeId)) {
      filteredAttendance.set(key, value);
    }
  }

  return { employees: filteredEmployees, attendance: filteredAttendance };
}
